import { Inter } from "next/font/google";
import { AppProvider } from "./context";
import Header from "./header/page";
import Footer from "./footer/page";
import Model from "./model";
import Cartmodal from "./cartmodal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bonik Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <Header />
          <Cartmodal />
          <Model />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
